version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: ticket-app
    restart: always
    environment:
      MYSQL_DATABASE: "tickets-app"
      MYSQL_USER: "****"
      MYSQL_PASSWORD: "****"
      MYSQL_ROOT_PASSWORD: "****"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
